name: datalab
channels:
  - conda-forge
  - nodefaults
dependencies:
  - sqlite
  - requests
  - pandas
  - jinja2
  - xarray
  - netcdf4
  - dask
  - matplotlib
  - basemap
  - cartopy
  - zarr
  - s3fs
  - seaborn
  - basemap
  - ipykernel
  - 'libnetcdf<4.9'
